pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.stack-work
    volumes:
      - /tmp/cache:/cache
    ttl: 7

  build:
    image: nrskt/haskell-build
    commands:
      - cd drone-haskell
      - stack build
      - stack test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.stack-work
    volumes:
      - /tmp/cache:/cache
    ttl: 7