pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ~/.stack
    volumes:
      - /tmp/cache:/cache
    ttl: 7

  build:
    image: fpco/stack-build:lts-9.10
    commands:
      - cd drone-haskell
      - ls -al ~/

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ~/.stack
    volumes:
      - /tmp/cache:/cache
    ttl: 7
